<a href="https://colab.research.google.com/github/ShlokGadhave/eda-and-data-visualization/blob/main/numpys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array([20,30,40])
b=np.array([30,40,50])
print(a)
print(b)
print(a+b)
print(a*b)
print(a-b)



[20 30 40]
[30 40 50]
[50 70 90]
[ 600 1200 2000]
[-10 -10 -10]


In [ ]:
l1=[20,30,40]
l2=[40,50,60]
print(l1+l2)

[20, 30, 40, 40, 50, 60]


In [ ]:
a=np.array([12,13,14.0])
print(a)
b=np.array([12,13,'14'])
print(b)


[12. 13. 14.]
['12' '13' '14']


In [ ]:
b=np.array([30,40,50])
print(type(b))
c=np.array([[40,50,60],[70,80,90]])
print(type(c))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
#Slicing in Numpy
b=np.array([10,20,30,40,50])
print(b[0:3])
print(b[3:])
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:2])
print(arr[0,0:2])
print(arr[1,0:2])

[10 20 30]
[40 50]
[[10 20]
 [50 60]]
[10 20]
[50 60]


In [ ]:
#Inspecting an Array
b=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(b.shape) #Shape=Structre of the array
print(b.size) #Number of elements in the list
print(np.ndim(b))
print(b.dtype)
print(len(b))
print(b.astype(float))

(3, 4)
12
2
int64
3
[[ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]]


In [ ]:
#Mathematical Operations

