<a href="https://colab.research.google.com/github/ShlokGadhave/eda-and-data-visualization/blob/main/numpys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array([20,30,40])
b=np.array([30,40,50])
print(a)
print(b)
print(a+b)
print(a*b)
print(a-b)



[20 30 40]
[30 40 50]
[50 70 90]
[ 600 1200 2000]
[-10 -10 -10]


In [ ]:
l1=[20,30,40]
l2=[40,50,60]
print(l1+l2)

[20, 30, 40, 40, 50, 60]


In [ ]:
a=np.array([12,13,14.0])
print(a)
b=np.array([12,13,'14'])
print(b)


[12. 13. 14.]
['12' '13' '14']


In [ ]:
b=np.array([30,40,50])
print(type(b))
c=np.array([[40,50,60],[70,80,90]])
print(type(c))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
#Slicing in Numpy
b=np.array([10,20,30,40,50])
print(b[0:3])
print(b[3:])
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:2])
print(arr[0,0:2])
print(arr[1,0:2])

[10 20 30]
[40 50]
[[10 20]
 [50 60]]
[10 20]
[50 60]


In [ ]:
#Inspecting an Array
b=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(b.shape) #Shape=Structre of the array
print(b.size) #Number of elements in the list
print(np.ndim(b))
print(b.dtype)
print(len(b))
print(b.astype(float))

(3, 4)
12
2
int64
3
[[ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]]


In [10]:
import numpy as np
arr=np.array([10,20,30])
arr1=np.array([40,50,60])
print(np.concatenate((arr,arr1)))
print(np.concatenate((arr,arr1),axis=0))


[10 20 30 40 50 60]
[10 20 30 40 50 60]


In [14]:
a=np.array([[20,30,40,50],[60,70,80,90]])
b=np.array([[10,20,30,40],[50,60,70,80]])
print(np.concatenate((a,b),axis=1))
print(np.hstack((a,b))) #horizontal Stack
print(np.vstack((a,b))) #vertical stack

[[20 30 40 50 10 20 30 40]
 [60 70 80 90 50 60 70 80]]
[[20 30 40 50 10 20 30 40]
 [60 70 80 90 50 60 70 80]]
[[20 30 40 50]
 [60 70 80 90]
 [10 20 30 40]
 [50 60 70 80]]


In [17]:
a=np.array([10,20,30,40,50,60])
print(np.array_split(a,3)) #3=number of parts
b=np.array([[10,20,30,40],[50,60,70,80]])
print(np.array_split(b,3))


[array([10, 20]), array([30, 40]), array([50, 60])]
[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]]), array([], shape=(0, 4), dtype=int64)]


In [27]:
a=np.array([100,200,300,400,500,600])
print(np.append(a,90))
print(np.append(a,80))
print(np.insert(a,1,70))
print(np.insert(a,5,9000))
print(np.delete(a,0))



[100 200 300 400 500 600  90]
[100 200 300 400 500 600  80]
[100  70 200 300 400 500 600]
[ 100  200  300  400  500 9000  600]
[200 300 400 500 600]
[100 200 300 400 500 600]


In [43]:
a=np.array([20,70,100,2,3,5])
print(np.sort(a))
print(np.where(a%2==0))
b=np.array([20,40,50,60,80])
print(np.searchsorted(b,50)) #array must be soreted in these





[  2   3   5  20  70 100]
(array([0, 1, 2, 3]),)
2


In [52]:
import numpy as np
a=np.array([10,20,30,40,50])
print(np.sum(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.min(a))
print(np.cumsum(a))
print(np.cumprod(a))


150
50
5
30.0
10
[ 10  30  60 100 150]
[      10      200     6000   240000 12000000]


In [61]:
import statistics as stats
baked_food=[100,200,300,500,600]
a=np.array(baked_food)
print(np.median(baked_food))
print(np.mean(baked_food))
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))
print(np.percentile(baked_food,25))


300.0
340.0
100
185.47236990991408
34400.0
200.0


In [68]:
Menu_card=[200,500,600,800,900]
Orders=[400,500,600,700,900]
a=np.array(Menu_card)
b=np.array(Orders)
print(np.sum((a,b),axis=1))
print(np.mean((a,b),axis=0))

[3000 3100]
[300. 500. 600. 750. 900.]
